In [3]:
import numpy as np

In [2]:
np.__version__

'1.17.4'

In [7]:
np1 = np.array([10,20,30])
np1

array([10, 20, 30])

In [8]:
np1.dtype

dtype('int64')

In [9]:
np1 = np.array([10,20,30.0])
np1

array([10., 20., 30.])

In [10]:
np1.dtype

dtype('float64')

### 只含有0的数组

In [12]:
# 默认dtype类型为float类型
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 指定填充的类型
np.zeros(shape=(2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros(shape=(2, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

### 只含有1的数组

In [22]:
# 默认dtype类型为float类型
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.ones(shape=(2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

### 自定义填充

In [28]:
np.full(shape=(3, 4), fill_value=2.0)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

### arange

In [34]:
# 不包括10
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [37]:
np.arange(10, 20, 0.9)

array([10. , 10.9, 11.8, 12.7, 13.6, 14.5, 15.4, 16.3, 17.2, 18.1, 19. ,
       19.9])

### linspace

In [38]:
# 从10到20(包括20)间，选择5个数据
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

### random

In [40]:
# 生成一个大小为8，取值范围在2到10（不包括10）间的随机数组
np.random.randint(2, 10, size=8)

array([3, 4, 3, 2, 8, 6, 3, 3])

In [41]:
np.random.randint(2, 10, size=(2, 5))

array([[2, 9, 8, 4, 4],
       [5, 9, 7, 7, 3]])

In [42]:
np.random.randint(2, 10, (2, 5))

array([[3, 6, 8, 4, 9],
       [6, 4, 3, 9, 5]])

In [43]:
np.random.randint(0, 1, 2)

array([0, 0])

In [44]:
# 在调试的时候，使每次随机生成的数是一样的
np.random.seed(123)
np.random.randint(2, 10, (2, 5))

array([[8, 7, 8, 4, 6],
       [4, 8, 3, 5, 4]])

In [46]:
# 生产随机数前，起一个参数，下次再次生成的时候之前再次调用这个参数
np.random.seed(123)
np.random.randint(2, 10, (2, 5))

array([[8, 7, 8, 4, 6],
       [4, 8, 3, 5, 4]])

In [48]:
np.random.random()

array([0.9807642 , 0.68482974, 0.4809319 , 0.39211752, 0.34317802])

In [49]:
np.random.random(4)

array([0.72904971, 0.43857224, 0.0596779 , 0.39804426])

In [50]:
np.random.random((3, 5))

array([[0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759],
       [0.63440096, 0.84943179, 0.72445532, 0.61102351, 0.72244338],
       [0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612]])

In [14]:
# 不打乱数组对象本身的顺序，而是返回一个新的打乱的数组
np.random.permutation(np.arange(16))

array([ 8,  7,  0,  1,  5, 15,  6, 13,  3,  2,  4, 12, 10,  9, 11, 14])

## 基本属性

In [2]:
import numpy as np
a = np.random.random((3, 5))
c = np.array([10,3,4,6])
print('a:{}'.format(a))
print('c:{}'.format(c))

a:[[0.4772262  0.96290308 0.76290074 0.66565535 0.23259353]
 [0.3529918  0.3515321  0.1805696  0.66810533 0.82173489]
 [0.61812957 0.05082177 0.59031836 0.94537604 0.66421475]]
c:[10  3  4  6]


In [3]:
# ndim：数组维度
print('a.ndim:{}'.format(a.ndim))
# shape：数组具体维度
print('a.shape:{}'.format(a.shape))
print('c.shape:{}'.format(c.shape))
# size：元素个数
print('c.size:{}'.format(c.size))
print('a.size:{}'.format(a.size))

a.ndim:2
a.shape:(3, 5)
c.shape:(4,)
c.size:4
a.size:15


## 基础操作

In [119]:
d = np.arange(10, 20, 1)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [108]:
d[0]

10

In [114]:
d[0:5]

array([10, 11, 12, 13, 14])

In [115]:
d[:5]

array([10, 11, 12, 13, 14])

In [116]:
d[::2]

array([10, 12, 14, 16, 18])

In [120]:
d[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [122]:
D = np.random.randint(2, 10, size=(3, 5))
D

array([[4, 9, 3, 2, 8],
       [5, 9, 3, 5, 9],
       [9, 2, 4, 5, 8]])

In [125]:
# 不推荐这种方式
D[0][1]

9

In [129]:
# 取第1行，第2列的数据
D[0, 1]

9

In [130]:
# 取两行三列的数组
D[:2, :3]

array([[4, 9, 3],
       [5, 9, 3]])

In [132]:
# 取两行，并将所有列反转
D[:2, ::-1]

array([[8, 2, 3, 9, 4],
       [9, 5, 3, 9, 5]])

In [133]:
D[::-1, ::-1]

array([[8, 5, 4, 2, 9],
       [9, 5, 3, 9, 5],
       [8, 2, 3, 9, 4]])

In [135]:
# 取第一行 D[0]
D[0]

array([4, 9, 3, 2, 8])

In [136]:
# 取第一行 D[0]
D[0, :]

array([4, 9, 3, 2, 8])

In [139]:
# 取第1列
D[:, 0]

array([4, 5, 9])

In [141]:
subD = D[:2, :3]
subD

array([[4, 9, 3],
       [5, 9, 3]])

In [146]:
# 原主矩阵的值也被修改，对numpy来说，利用引用的方式来获取数据
subD[0, 0] = 400
subD

array([[400,   9,   3],
       [  5,   9,   3]])

In [147]:
D

array([[400,   9,   3,   2,   8],
       [  5,   9,   3,   5,   9],
       [  9,   2,   4,   5,   8]])

In [149]:
D[0, 0] = 100
D

array([[100,   9,   3,   2,   8],
       [  5,   9,   3,   5,   9],
       [  9,   2,   4,   5,   8]])

In [150]:
subD

array([[100,   9,   3],
       [  5,   9,   3]])

In [151]:
# 可以利用copy方式来复制一个新的数组
subD2 = D[:2, :3].copy()
subD2

array([[100,   9,   3],
       [  5,   9,   3]])

In [153]:
subD2[0, 0] = 33
subD2

array([[33,  9,  3],
       [ 5,  9,  3]])

In [154]:
D

array([[100,   9,   3,   2,   8],
       [  5,   9,   3,   5,   9],
       [  9,   2,   4,   5,   8]])

In [165]:
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [166]:
# 改变数组的维度：reshape
d.size

10

In [160]:
d_reshape = d.reshape(2, 5)
d_reshape

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [157]:
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [158]:
d.shape

(10,)

In [161]:
d_reshape.shape

(2, 5)

In [164]:
# 只关心行，自动计算列 -1
d.reshape(10, -1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [169]:
# 只关心列，自动计算行 -1
d.reshape(-1, 10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [170]:
d.reshape(2, -1)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [172]:
# 4无法被d.size所整除
d.reshape(4, -1)

ValueError: cannot reshape array of size 10 into shape (4,newaxis)

In [173]:
D

array([[100,   9,   3,   2,   8],
       [  5,   9,   3,   5,   9],
       [  9,   2,   4,   5,   8]])

In [175]:
D.reshape(5, -1)

array([[100,   9,   3],
       [  2,   8,   5],
       [  9,   3,   5],
       [  9,   9,   2],
       [  4,   5,   8]])

In [176]:
D.reshape(-1, 3)

array([[100,   9,   3],
       [  2,   8,   5],
       [  9,   3,   5],
       [  9,   9,   2],
       [  4,   5,   8]])

## 合并

In [178]:
x = np.random.randint(2, 10, (2, 5))
x

array([[9, 7, 8, 5, 6],
       [9, 8, 2, 9, 7]])

In [179]:
y = np.random.randint(2, 10, (2, 5))
y

array([[7, 2, 2, 9, 5],
       [3, 2, 4, 3, 9]])

In [181]:
# 拼接
np.concatenate((x, y))

array([[9, 7, 8, 5, 6],
       [9, 8, 2, 9, 7],
       [7, 2, 2, 9, 5],
       [3, 2, 4, 3, 9]])

In [182]:
# 默认按照第一个维度（行）的方向
np.concatenate((x, y), axis=0)

array([[9, 7, 8, 5, 6],
       [9, 8, 2, 9, 7],
       [7, 2, 2, 9, 5],
       [3, 2, 4, 3, 9]])

In [183]:
# 按照列维度的方向拼接
np.concatenate((x, y), axis=1)

array([[9, 7, 8, 5, 6, 7, 2, 2, 9, 5],
       [9, 8, 2, 9, 7, 3, 2, 4, 3, 9]])

In [190]:
z = np.arange(5)
z

array([0, 1, 2, 3, 4])

In [192]:
np.concatenate((x, z.reshape(1, -1)))

array([[9, 7, 8, 5, 6],
       [9, 8, 2, 9, 7],
       [0, 1, 2, 3, 4]])

In [193]:
# 纵向合并（要求列数一样）
np.vstack((x, z))

array([[9, 7, 8, 5, 6],
       [9, 8, 2, 9, 7],
       [0, 1, 2, 3, 4]])

In [212]:
# 横向合并（要求行数一样）
np.hstack((x, np.random.randint(0, 8, size=(2, 3))))

array([[9, 7, 8, 5, 6, 4, 0, 0],
       [9, 8, 2, 9, 7, 4, 6, 0]])

In [210]:
np.random.randint(0, 8, size=(2, 3))

array([[3, 5, 1],
       [6, 0, 0]])

## 分割

In [213]:
x = np.arange(10)

In [215]:
# 从第4个元素开始分割，分成两部分
np.split(x, (3,))

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9])]

In [216]:
# 从在4个元素和第8个元素处分割，分成三部分
np.split(x, (3, 7))

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [223]:
X = np.arange(15).reshape((5, -1))
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [224]:
np.split(X, (1, 3))

[array([[0, 1, 2]]), array([[3, 4, 5],
        [6, 7, 8]]), array([[ 9, 10, 11],
        [12, 13, 14]])]

In [226]:
# 垂直方向上分割
np.split(X, (2,), axis=1)

[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])]

In [232]:
upper, lower = np.vsplit(X, (2,))
upper

array([[0, 1, 2],
       [3, 4, 5]])

In [233]:
lower

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [230]:
left, right = np.hsplit(X, (2, ))
left

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [231]:
right

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]])

In [236]:
A = np.arange(28).reshape(7, -1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [248]:
A[:, :A.shape[1]-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22],
       [24, 25, 26]])

In [244]:
A[:, -1]

array([ 3,  7, 11, 15, 19, 23, 27])

In [252]:
left, right = np.hsplit(A, (-1,))
left

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22],
       [24, 25, 26]])

In [253]:
right.reshape(-1)

array([ 3,  7, 11, 15, 19, 23, 27])

## 运算

### 矩阵与数值运算

In [266]:
%%time
L = [i for i in range(10000)]
A = []
for j in L:
    A.append(2*j)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 1.82 ms


In [275]:
%%time
L = np.arange(10000)
A = np.array(2*i for i in L)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 112 µs


In [276]:
%%time
A = 2 * L # 向量的运算

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 93.2 µs


In [301]:
X = np.arange(1, 16).reshape(3, -1)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [302]:
X - 1 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [303]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [315]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [304]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [316]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [305]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [306]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [307]:
# 3的X的中的方
3**X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [308]:
# 3的X的中的方
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [309]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [310]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [311]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [312]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [313]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [314]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵与矩阵运算

In [319]:
A = np.arange(1, 10).reshape(3, -1)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [323]:
B = np.full((3, 3), 10)
B

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [324]:
A + B

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [325]:
A - B

array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])

In [326]:
# 并非真正的矩阵间的乘法，仅仅是相同位置处的元素相乘
A * B

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [328]:
# 数据定义上的矩阵间的乘法运算
A.dot(B)

array([[ 60,  60,  60],
       [150, 150, 150],
       [240, 240, 240]])

### 向量与矩阵间的运算

In [358]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [359]:
M = np.arange(9).reshape(3, -1)
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [360]:
# 实际上是在M的基础上每一行都去加上了c
c + M

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [361]:
# 也可以先转化为跟M同行同列之后再运算
c1 = np.vstack([c] * M.shape[0])
c1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [362]:
c1 + M

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [363]:
# 或者使用title方法去堆叠，以下为在行向上堆叠M.shape[0]次，在列向上堆叠一次
np.tile(c, (M.shape[0], 1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [364]:
# 仍然是相应位置上元素间的乘法
c * M

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

In [370]:
# 数学意义上的乘法
c.dot(M)

array([24, 30, 36])

In [372]:
# 讲c自动看作了一个列向量
M.dot(c)

array([ 8, 26, 44])

### 逆矩阵

In [384]:
# 前提条件是方阵
M = np.array([[1, 2],[3, 4]])
M

array([[1, 2],
       [3, 4]])

In [383]:
invA = np.linalg.inv(M)
invA

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [390]:
# 但是可以求伪逆矩阵
A = np.arange(4).reshape(2, -1)
A

array([[0, 1],
       [2, 3]])

In [396]:
#互为逆矩阵相乘得单位矩阵
pinvA.dot(A) # 等于A.dot(pinvA)

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

### 聚合运算

In [398]:
M = np.random.random(100)

In [405]:
%timeit sum(M)
%timeit np.sum(M)

31 µs ± 617 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
4.9 µs ± 71.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [406]:
np.max(M)

0.9989184059727976

In [407]:
np.min(M)

0.006027885653297926

In [408]:
M.min()

0.006027885653297926

In [409]:
M.max()

0.9989184059727976

In [413]:
# sum默认是对所有的元素进行操作
M.sum()

46.87023495066829

In [414]:
X = np.arange(16).reshape(8, 2)
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [416]:
# 沿着第一个维度(行)，做计算
np.sum(X, axis=0)

array([56, 64])

In [417]:
# 沿着第二个维度(列)，做计算
np.sum(X, axis=1)

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [419]:
# 所有元素相应的乘积
np.prod(X)

0

In [420]:
np.prod(X+1)

20922789888000

In [421]:
# 平均值
np.mean(X)

7.5

In [422]:
# 中位数
np.median(X)

7.5

In [423]:
# 在M中，50%的值是小于0.4157328873696228
np.percentile(M, q=50)

0.4157328873696228

In [424]:
np.percentile(M, q=100)

0.9989184059727976

In [426]:
np.max(M)

0.9989184059727976

In [427]:
# 方差
np.var(M)

0.08691870045544972

In [428]:
# 标准差
np.std(M)

0.29481977622854566

In [440]:
# 创建一个均值为0，标准差为1的正太分布
C = np.random.normal(0, 1, size=10000)
C

array([-1.1676343 ,  0.68148702, -1.52051696, ..., -0.88844972,
       -1.02077306, -0.26432358])

In [446]:
# 标准差接近于1
np.std(C)

1.0024630798175147

In [447]:
# 均值接近于0
np.mean(C)

0.0019506567168924966

### 排序运算

In [448]:
m = np.random.normal(0, 1, size=10000)
m

array([ 0.09512025,  0.4755045 , -1.47252749, ..., -0.72446627,
        0.13108296,  0.05026143])

In [449]:
m.min()

-3.9278297627787047

In [453]:
# 最小值的索引
m.argmin()

8671

In [454]:
m[8671]

-3.9278297627787047

In [455]:
m[m.argmax()]

3.5980679544021075

In [464]:
x = np.arange(16)
np.random.shuffle(x)
x

array([12, 15,  1, 13,  6, 11,  4,  9,  3, 10,  0, 14,  5,  2,  8,  7])

In [471]:
# 生成一个新的数组
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [472]:
# 改变x的顺序
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [487]:
a = np.random.randint(1, 20, (3, 5))
a

array([[ 9,  2,  7,  3, 17],
       [17, 15, 18,  2,  9],
       [ 2,  2, 13,  8,  4]])

In [490]:
# 默认axis为1
np.sort(a, axis=1)

array([[ 2,  3,  7,  9, 17],
       [ 2,  9, 15, 17, 18],
       [ 2,  2,  4,  8, 13]])

In [491]:
np.sort(a, axis=0)

array([[ 2,  2,  7,  2,  4],
       [ 9,  2, 13,  3,  9],
       [17, 15, 18,  8, 17]])

In [492]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [497]:
np.random.shuffle(x)
x

array([ 4, 13,  8,  0, 11,  3,  6, 12,  7,  1, 14,  9, 10, 15,  2,  5])

In [499]:
# 按照索引值排序
np.argsort(x)

array([ 3,  9, 14,  5,  0, 15,  6,  8,  2, 11, 12,  4,  7,  1, 10, 13])

In [505]:
# 快排中，partition函数，在某个值的左边放比其小的，在右边放比其大的数据，但是并不一定是有序的
np.partition(x, 2)

array([ 0,  1,  2,  4, 11,  3,  6, 12,  7, 13, 14,  9, 10, 15,  8,  5])

In [507]:
# 2 在x中的索引是14，14左边的索引代表的值都比14代表的值小，右边则大
np.argpartition(x, 2)

array([ 3,  9, 14,  0,  4,  5,  6,  7,  8,  1, 10, 11, 12, 13,  2, 15])

In [510]:
X = np.random.shuffle
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [516]:
a

array([[ 9,  2,  7,  3, 17],
       [17, 15, 18,  2,  9],
       [ 2,  2, 13,  8,  4]])

In [518]:
np.argsort(a, axis=1)

array([[1, 3, 2, 0, 4],
       [3, 4, 1, 0, 2],
       [0, 1, 4, 3, 2]])

In [519]:
np.argsort(a, axis=0)

array([[2, 0, 0, 1, 2],
       [0, 2, 2, 0, 1],
       [1, 1, 1, 2, 0]])

In [520]:
np.argpartition(a, 2, axis=1)

array([[1, 3, 2, 0, 4],
       [3, 4, 1, 0, 2],
       [0, 1, 4, 3, 2]])

### fancy indexing

In [16]:
a = np.random.randint(1, 10, (10,))
a

array([8, 1, 3, 1, 9, 3, 4, 5, 6, 4])

In [529]:
# index访问多个数据
a[[2,3,4]]

array([3, 6, 8])

In [533]:
# 创建一个二维索引矩阵
index = np.array([[1, 2],[6, 8]])
a[index]

array([[4, 3],
       [9, 8]])

In [557]:
a[[[1, 2],[6, 8]]]

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


IndexError: too many indices for array

In [4]:
c = np.arange(16).reshape(4, -1)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
c[np.array([1,2])]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
c[[1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [543]:
col = np.array([0, 2])

In [544]:
c[1, col]

array([4, 6])

In [545]:
row = np.array([2, 3])

In [546]:
c[row, col]

array([ 8, 14])

In [548]:
c[:3, col]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [551]:
c[:3, [0, 2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [554]:
c[:3, [True, False, True, False]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### 比较

In [568]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [572]:
A = a.reshape(4, -1)
A


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [573]:
a != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [574]:
a > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [575]:
a == 4

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [576]:
2 * a == 24 - 3 * a

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [577]:
A < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [578]:
# 小于6的元素的个数
np.sum(a < 6)

6

In [580]:
# 查看非零元素的个数
np.count_nonzero(a < 6)

6

In [584]:
# 是否有真（True），只要有一个为真，即为True
np.any(a == 0)

True

In [586]:
# 是否所有为真（True），有一个False则为false
np.all(a == 0)

False

In [589]:
np.all(a[1:])

True

In [590]:
# 查看偶数的个数
np.sum(a % 2 == 0)

8

In [595]:
np.sum(A, axis=1)

array([ 6, 22, 38, 54])

In [596]:
np.sum(A, axis=0)

array([24, 28, 32, 36])

In [600]:
# 沿行方向
np.sum(A % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [601]:
# 沿列方向
np.sum(A % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [603]:
# 查看沿着行方向上，大于0的数据情况
np.all(A > 0, axis=0)

array([False,  True,  True,  True])

In [613]:
# 大于3且小于10的个数
cond = (A % 3 ==0 ) | (A > 10)
cond

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])

In [617]:
# 查看满足条件的具体数据
A[cond]

array([ 0,  3,  6,  9, 11, 12, 13, 14, 15])

In [616]:
# 查看满足条件的数量
np.sum((A > 3) & (A < 10))

9

In [618]:
np.sum(cond)

9

In [619]:
# 不等于0的个数
np.sum(~(A == 0))

15

In [620]:
A[~(A == 0)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [625]:
# 最后一列中能被3整除的数组
# 1：A[:, -1] % 3 == 0 ==> array([ True, False, False,  True])
A[A[:, -1] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [10]:
import numpy as np
a = np.random.randint(0, 10, (2, 5))
len(a)

2